name: Merge XML Files

on:
  schedule:
    - cron: '5 0 * * *'  # Exécuter tous les jours à 00:05
  workflow_dispatch:  # Permet également de déclencher manuellement l'action depuis GitHub

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code depuis GitHub
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Étape 3 : Exécuter le script Python pour fusionner les fichiers XML
      - name: Run merge_xml.py script
        run: |
          python merge_xml.py

      # Étape 4 : Configurer Git et l'authentification via GH_TOKEN
      - name: Set up Git authentication
        uses: actions/configure-git@v2
        with:
          git_user_name: 'GitHub Actions'
          git_user_email: 'actions@github.com'

      # Étape 5 : Committer et pousser les fichiers
      - name: Commit and push merged XML file
        run: |
          git add xmltv_full.xml
          git commit -m "Fusion des fichiers XML automatique"
          # Utiliser GH_TOKEN pour authentification
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
