name: Merge XML Files

on:
  schedule:
    - cron: '5 0 * * *'  # Exécuter tous les jours à 00:05
  workflow_dispatch:  # Permet également de déclencher manuellement l'action depuis GitHub

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code depuis GitHub
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Étape 3 : Installer les dépendances si nécessaire (dans ce cas, aucune pour ce script simple)
      # Si tu as des dépendances (comme `lxml` ou autre), tu pourrais les ajouter ici
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Si tu as un fichier requirements.txt

      # Étape 4 : Exécuter le script Python pour fusionner les fichiers XML
      - name: Run merge_xml.py script
        run: |
          python merge_xml.py

      # Étape 5 : Ajouter et commiter le fichier fusionné
      - name: Commit and push merged XML file
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add xmltv_full.xml
          git commit -m "Fusion des fichiers XML automatique"
          git push
