name: Merge XML Files

on:
  schedule:
    - cron: '5 0 * * *'  # Exécuter tous les jours à 00:05
  workflow_dispatch:  # Permet également de déclencher manuellement l'action depuis GitHub

permissions:
  contents: write  # Permet d'effectuer un push sur le dépôt
  
jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run merge_xml.py script
        run: python merge_xml.py

      - name: Commit and push the changes
        run: |
          git config --global user.email "youremail@example.com"
          git config --global user.name "Your Name"
          git add xmltv_full.xml
          git commit -m "Fusion des fichiers XML automatique"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/d32k18/xmltv.git

